name: Python CI

on: [push, pull_request]

jobs:
  build:
    environment: smashing-download
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.x
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Publish code coverage report
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test
